src/Entity/Blog.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BlogRepository")
 */
class Blog
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     *
     */
    private $user;

    /**
     * @ORM\Column(type="string", length=40)
     * @Assert\NotBlank(message="Title cannot be empty.")
     * @Assert\Length(max=40)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     * @Assert\Length(max=255)
     */
    private $short_description;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank()
     */
    private $body;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     * @Assert\Image()
     */
    private $image;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getShortDescription(): ?string
    {
        return $this->short_description;
    }

    public function setShortDescription(string $short_description): self
    {
        $this->short_description = $short_description;

        return $this;
    }

    public function getBody(): ?string
    {
        return $this->body;
    }

    public function setBody(string $body): self
    {
        $this->body = $body;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Welcome!{% endblock %}</title>
    <link rel="icon"
          href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    {% block stylesheets %}
        <style>
            body {
                font-family: 'Open Sans', sans-serif;
            }

            .btn, .back-btn {
                margin-bottom: 20px;
                margin-top: 10px;
            }

            .table {
                margin-top: 10px;
            }

            .align-center {
                margin: 0 auto;
            }

            .header-bg {
                width: 100vw;
                background-color: #09162b;
                transform: skewY(-8deg);
                margin-top: -140px;
                margin-bottom: -100px;
                height: 350px;
                padding-bottom: 50px;
            }

            .header-title {
                color: white;
                font-family: 'Raleway', sans-serif;
                font-weight: 800 !important;
            }

            .language-menu {
                position: relative;
                text-align: right;
            }

            .language-menu a {
                margin-left: 20px;
            }

            .language-menu .active {
                font-weight: bold;
                padding-bottom: 5px;
                border-bottom: 2px solid #007bff;
            }

            .post_count {
                float: right;
                padding-top: 15px;
            }

            .custom-container {
                background-color: whitesmoke !important;
                z-index: 1;
                position: relative;
                width: 70%;
                margin-left: 15%;
                margin-top: 15px;
                box-shadow: 10px 10px 10px grey;
                border-radius: 30px;
                padding: 50px 0px;
            }

            .btn-dark, .table .thead-dark th {
                background-color: #09162b;
            }

            label {
                font-weight: bold;
            }

            .register-link {
                float: right;
                margin-top: 20px;
            }

            .blog-foot {
                font-size: 15px;
                margin-top: 50px;
            }

            .footer{
                width: 100vw;
                height: 100px;
                background-color: white;
                margin-top: 50px;
            }
        </style>
    {% endblock %}

    {% block javascripts %}
        <script src="https://kit.fontawesome.com/0e1301bd15.js" crossorigin="anonymous"></script>
    {% endblock %}
</head>
<body>
<div class="header">
    <div class="header-bg"></div>
    <div class="col-lg-8 align-center header-title">
        {% block headertitle %}{% endblock %}
    </div>
</div>

{% block languages %}
    {% include 'languages.html.twig' %}

{% endblock %}

{% block body %}{% endblock %}
{% block footer %}
    <div class="footer"></div>
{% endblock %}
</body>
</html>

templates/create.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="header"></div>
    <div class="col-lg-8 align-center header-title">
        <h1>New post</h1>
    </div>
    <div class="custom-container">
<div class="row">
    <div class="col-lg-10 align-center">
        {% for label, messages in app.flashes %}
            {% for message in messages %}
                <div class="flash-{{ label }}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endfor %}
        {{ form_start(form) }}

        <div class="form-group">
            <label>Title</label>
            {{ form_widget(form.title) }}
        </div>
        <div class="form-group">
            <label>Short Description</label>
            {{ form_widget(form.shortDescription) }}
        </div>
{#        <div class="form-group">#}
{#            <label>Author</label><br>#}
{#            {{ user.id }}#}
{#        </div>#}
{#        <div class="form-group">#}
{#            {{ form_widget(form.imageFile) }}#}
{#        </div>#}
        <div class="form-group">
            <label>Text</label>
            {{ form_widget(form.body) }}
        </div>

        <button type="submit" class="btn btn-dark">Submit</button>
        <a href="{{ path('app_main_index') }}">Back to overview</a>



        {{ form_end(form) }}
    </div>
</div>
    </div>
{% endblock %}

templates/languages.html.twig
<div class="language-menu col-lg-8 align-center">
    {% if app.request.locale == 'en' %}
        <a href="{{ path(app.request.get('_route'), app.request.get('_route_params')|merge({'_locale': 'nl'})) }}">Nederlands</a>
        <a class="active"
           href="{{ path(app.request.get('_route'), app.request.get('_route_params')|merge({'_locale': 'en'})) }}">English</a>
    {% endif %}

    {% if app.request.locale == 'nl' %}
        <a class="active"
           href="{{ path(app.request.get('_route'), app.request.get('_route_params')|merge({'_locale': 'nl'})) }}">Nederlands</a>
        <a href="{{ path(app.request.get('_route'), app.request.get('_route_params')|merge({'_locale': 'en'})) }}">English</a>
    {% endif %}
    {% if is_granted('ROLE_USER') %}
        <a href="{{ path('app_logout') }}" class="fas fa-sign-out-alt" title="logoff"></a>
    {% else %}
        <a href="{{ path('login') }}" class="fas fa-sign-in-alt" title="login"></a>
    {% endif %}
</div>